#!/bin/bash

# format.sh — apply the repo's source formatting rules in place.
#
# Two passes over the same file set:
#   1. clang-format, using the .clang-format at the repo root (Google style,
#      2-space indent, 80 columns).
#   2. strip trailing whitespace, which also covers Lexer.l / Parser.y —
#      clang-format cannot parse flex/bison sources, so those get pass 2 only.
#
# src/generated/ is never touched. Those files are regenerated by flex and bison
# on every CMake configure, so any edit here would be reverted by the next build
# and show up as thousands of lines of phantom local modifications. (There is a
# src/generated/.clang-format setting DisableFormat as a second guard, but the
# trailing-whitespace pass would ignore it, hence the explicit prune below.)
#
# Modes:
#   (default)   rewrite files in place
#   --check     report what would change and exit 1 without writing; for CI
#
# Usage:
#   ./format.sh
#   ./format.sh --check

set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
source "${script_dir}/build-env.sh" || exit 1

repo_root="$(cd "${script_dir}/.." && pwd)"

check_only=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      check_only=true
      shift
      ;;
    -h|--help)
      echo "Usage: $0 [--check]" >&2
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      echo "Usage: $0 [--check]" >&2
      exit 1
      ;;
  esac
done

if ! command -v clang-format >/dev/null 2>&1; then
  echo "clang-format not found. Install LLVM 20; see docs/Install.md." >&2
  echo "  macOS:  brew install llvm@20        (ships clang-format)" >&2
  echo "  Ubuntu: sudo apt install clang-format-20" >&2
  exit 1
fi

# Print the binary and version: different clang-format majors disagree on
# layout, so a --check failure on one machine and not another is almost always
# version skew rather than a real formatting slip. Saying which one ran turns
# that from a puzzle into a one-line diagnosis.
clang_format_version="$(clang-format --version)"
echo "Using $(command -v clang-format) — ${clang_format_version}"
case "${clang_format_version}" in
  *" 20."*) ;;
  *) echo "Warning: lcc's .clang-format is maintained against clang-format 20;" \
          "another major version may report differences that are not real." >&2 ;;
esac

# GNU sed takes -i; BSD sed (macOS) requires an explicit empty suffix.
if sed --version >/dev/null 2>&1; then
  sed_inplace=(sed -i)
else
  sed_inplace=(sed -i '')
fi

# Roots that hold hand-written sources. src/generated is pruned by name.
roots=("${repo_root}/src" "${repo_root}/tests" "${repo_root}/benchmarks")

# clang-format handles C and C++; flex/bison sources get whitespace only.
list_clang_format_files() {
  find "${roots[@]}" \
    -type d -name generated -prune -o \
    -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.hpp' \) -print
}

list_whitespace_files() {
  find "${roots[@]}" \
    -type d -name generated -prune -o \
    -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.hpp' \
               -o -name '*.l' -o -name '*.y' \) -print
}

status=0

if [[ "$check_only" == true ]]; then
  while IFS= read -r file; do
    if ! clang-format "$file" | diff -q - "$file" >/dev/null 2>&1; then
      echo "needs clang-format: ${file#${repo_root}/}"
      status=1
    fi
  done < <(list_clang_format_files | sort)

  while IFS= read -r file; do
    if grep -qE '[[:blank:]]+$' "$file"; then
      echo "trailing whitespace:  ${file#${repo_root}/}"
      status=1
    fi
  done < <(list_whitespace_files | sort)

  if [[ "$status" -eq 0 ]]; then
    echo "All files are formatted."
  fi
  exit "$status"
fi

formatted=0
while IFS= read -r file; do
  clang-format -i "$file" || exit 1
  formatted=$((formatted + 1))
done < <(list_clang_format_files | sort)

# After clang-format, so this pass has the final say and also reaches .l / .y.
stripped=0
while IFS= read -r file; do
  if grep -qE '[[:blank:]]+$' "$file"; then
    "${sed_inplace[@]}" -E 's/[[:blank:]]+$//' "$file" || exit 1
    stripped=$((stripped + 1))
  fi
done < <(list_whitespace_files | sort)

echo "clang-format applied to ${formatted} file(s); trailing whitespace stripped from ${stripped}."
